package com.olga.droidsgame.constants;

public class DriodConstants {
	public static final Integer BASIC_VALUE = 10;
	public static final Integer COEFICIENT_BATTLE_DROID=3;
	public static final Integer COEFICIENT_REPAIR_DROID=2;
	public static final Integer COEFICIENT_SUPER_DROID=4;
	public static final Integer COEFICIENT_CHARGE_DROID=1;
	public static final Integer COEFICIENT_DEFENDER_BETTLE_DROID=2;
	public static final Integer COEFICIENT_SUPER_DOCTOR=1;
	public static final Integer COEFICIENT_BATTLE_LAZER_DROID=4;
	public static final Integer COEFICIENT_DEFENDER_DROID=1;
	public static final Integer COEFICIENT_DEFENDER_REPAIR_DROID=3;
	public static final Integer COEFICIENT_DROIDEKA_DROID=5;
	public static final Integer COEFICIENT_SUPER_POWERFULL_DROID=5;
	
	public static final Integer MAX_BEGIN_BATTLE_DROID_ENERGY = BASIC_VALUE * COEFICIENT_BATTLE_DROID;
	public static final Integer MAX_BEGIN_BATTLE_DROID_HEALTH = BASIC_VALUE * COEFICIENT_BATTLE_DROID;
	
	public static final Integer MAX_BEGIN_REPAIR_DROID_ENERGY = BASIC_VALUE * COEFICIENT_REPAIR_DROID;
	public static final Integer MAX_BEGIN_REPAIR_DROID_HEALTH = BASIC_VALUE * COEFICIENT_REPAIR_DROID;
		
	public static final Integer MAX_BEGIN_SUPER_DROID_ENERGY = BASIC_VALUE * COEFICIENT_SUPER_DROID;
	public static final Integer MAX_BEGIN_SUPER_DROID_HEALTH = BASIC_VALUE * COEFICIENT_SUPER_DROID;
	
	public static final Integer MAX_BEGIN_CHARGE_DROID_ENERGY = BASIC_VALUE * COEFICIENT_CHARGE_DROID;
	public static final Integer MAX_BEGIN_CHARGE_DROID_HEALTH = BASIC_VALUE * COEFICIENT_CHARGE_DROID;
	
	public static final Integer MAX_BEGIN_DEFENDER_BETTLE_DROID_ENERGY = BASIC_VALUE * COEFICIENT_DEFENDER_BETTLE_DROID;
	public static final Integer MAX_BEGIN_DEFENDER_BETTLE_DROID_HEALTH = BASIC_VALUE * COEFICIENT_DEFENDER_BETTLE_DROID;
	
	public static final Integer MAX_BEGIN_SUPER_DOCTOR_ENERGY = BASIC_VALUE * COEFICIENT_SUPER_DOCTOR;
	public static final Integer MAX_BEGIN_SUPER_DOCTOR_HEALTH = BASIC_VALUE * COEFICIENT_SUPER_DOCTOR;
	
	public static final Integer MAX_BEGIN_BATTLE_LAZER_DROID_ENERGY = BASIC_VALUE * COEFICIENT_BATTLE_LAZER_DROID;
	public static final Integer MAX_BEGIN_BATTLE_LAZER_DROID_HEALTH = BASIC_VALUE * COEFICIENT_BATTLE_LAZER_DROID;
	
	public static final Integer MAX_BEGIN_DEFENDER_DROID_ENERGY = BASIC_VALUE * COEFICIENT_DEFENDER_DROID;
	public static final Integer MAX_BEGIN_DEFENDER_DROID_HEALTH = BASIC_VALUE * COEFICIENT_DEFENDER_DROID;
	
	public static final Integer MAX_BEGIN_DEFENDER_REPAIR_DROID_ENERGY = BASIC_VALUE * COEFICIENT_DEFENDER_REPAIR_DROID;
	public static final Integer MAX_BEGIN_DEFENDER_REPAIR_DROID_HEALTH = BASIC_VALUE * COEFICIENT_DEFENDER_REPAIR_DROID;
	
	public static final Integer MAX_BEGIN_DROIDEKA_DROID_ENERGY = BASIC_VALUE * COEFICIENT_DROIDEKA_DROID;
	public static final Integer MAX_BEGIN_DROIDEKA_DROID_HEALTH = BASIC_VALUE * COEFICIENT_DROIDEKA_DROID;
	
	public static final Integer MAX_BEGIN_SUPER_POWERFULL_DROID_ENERGY = BASIC_VALUE * COEFICIENT_SUPER_POWERFULL_DROID;
	public static final Integer MAX_BEGIN_SUPER_POWERFULL_DROID_HEALTH = BASIC_VALUE * COEFICIENT_SUPER_POWERFULL_DROID;

	private DriodConstants() {}
}
